server:
  port: 8081

spring:
  application:
    name: taskflow-ecommerce-api
  datasource:
    driver-class-name: org.postgresql.Driver 
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level: 
    root: DEBUG
